<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<!DOCTYPE tei [
    <!ELEMENT tei (header, facsimile?, text+) >
    <!ELEMENT header (#PCDATA) >
    <!ELEMENT facsimile (#PCDATA) >
    <!ELEMENT text (#PCDATA | seg)* >
    <!ELEMENT seg (#PCDATA) >

    <!ATTLIST header type CDATA #FIXED "intestazione" >
    <!ATTLIST header lang NMTOKEN  #IMPLIED >

    <!ATTLIST facsimile source CDATA #REQUIRED >
    <!ATTLIST facsimile ref IDREFS #IMPLIED >

    <!ATTLIST text id ID #REQUIRED>
    <!ATTLIST text type CDATA #IMPLIED>

]>

<tei>
    <header>
        testo dell'header
    </header>

    <facsimile source="fonte" ref="id1">
        blabla del facsimile.
    </facsimile>

    <text id="id1">
        blabla del text id1.
    </text>
    <text id="id2">
        <seg>bla bla del seg</seg>
    </text>

</tei>